name: twist_food
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #  service
  dio: ^4.0.6
  json_serializable: ^6.5.4

  # db
  sqflite: ^2.2.2
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15

  # state management
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  equatable: ^2.0.5

  # route management
  get: ^4.6.5
  
  # ui
  shimmer: ^2.0.0
  fluttertoast: ^8.1.2
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  sms_autofill: ^2.2.0
  flutter_svg: ^1.1.6
  lottie: ^2.2.0
  pull_to_refresh: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  flutter_native_splash: ^2.2.16

  #location lib set up
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3

  # fonts:
  google_fonts: ^3.0.1
  
  #language
  easy_localization: ^3.0.1


    

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/


  fonts:
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
 
